site_name: SoftPack Core
site_url: https://wtsi-hgi.github.io/softpack-core
repo_url: https://github.com/wtsi-hgi/softpack-core
repo_name: wtsi-hgi/softpack-core
#strict: true
nav:
  - Introduction: index.md
  - Topics:
    - topics/design.md
  - Tutorials:
    - tutorials/getting_started.md
  - Guides:
      - guides/how-to-start-a-build.md
  - Reference:
    - reference/cli.md
    - reference/api.md
    - reference/rest.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  logo: img/softpack.png
  favicon: img/favicon.ico
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.footer
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 3
      permalink: true
  - meta
plugins:
  - include-markdown
  - render_swagger
  - search:
      lang: en
watch:
  - softpack_core
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wtsi-hgi/softpack-core
      name: Github
    - icon: material/email
      link: "mailto:altaf.ali@sanger.ac.uk"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
