server:
  host: 0.0.0.0
  port: 8000

  header:
    origins:
      - http://localhost
      - http://localhost:8080
      - http://localhost:3000

vault:
    url:
    path:
    token:

ldap:
  server:
  base:
  filter:
  group:
    attr:
    pattern:
