server:
  host: 0.0.0.0
  port: 8000

  header:
    origins:
      - http://localhost
      - http://localhost:8080
      - http://localhost:3000
      - http://localhost:5173

builder:
  host: 0.0.0.0
  port: 8001

artifacts:
  repo:
    url: https://github.com/mjkw31/softpack-artifacts
    username: softpack-core
    author: softpack
    email: softpack@sanger.ac.uk
  path: ./softpack-artifacts

spack:
  repo: https://github.com/custom-spack/repo
  bin: /path/to/spack

recipes:
  toAddr: none@domain.com
  fromAddr: "{}@domain.com"
  smtp: some.mail.relay

environments:
  toAddr: "{}@domain.com"
  fromAddr: "none@domain.com"
  smtp: some.mail.relay


# Vault Config
#  vault:
#      url:
#      path:
#      token:

# LDAP Config
#  ldap:
#    server:
#    retries:
#    base:
#    filter:
#    group:
#      attr:
#      pattern:
